#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, LT(5,KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, BL_STEP, KC_LCTL, KC_LALT, KC_LGUI, MO(3), KC_SPC, KC_SPC, MO(4), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),

[_LAYER1] = LAYOUT(KC_GRV, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_COLN, KC_BSPC, LT(5,KC_TAB), KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_QUES, LSFT_T(KC_ENT), BL_STEP, KC_LCTL, KC_LALT, KC_LGUI, MO(3), KC_SPC, KC_SPC, MO(4), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),

[_LAYER2] = LAYOUT(KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC, KC_ESC, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_SLSH, KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_ENT, BL_STEP, KC_LCTL, KC_LALT, KC_LGUI, MO(3), KC_RSFT, KC_SPC, MO(4), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),

[_LAYER3] = LAYOUT(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_LBRC, KC_RBRC, KC_AMPR, KC_ASTR, KC_9, KC_SCLN, KC_CAPS, KC_QUES, KC_F5, KC_F6, KC_F7, KC_F8, KC_LPRN, KC_EQL, KC_DLR, KC_PERC, KC_CIRC, KC_LCBR, KC_PIPE, KC_TRNS, KC_F9, KC_F10, KC_F11, KC_F12, KC_MINS, KC_PLUS, KC_EXLM, KC_AT, KC_HASH, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(6), KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY),

[_LAYER4] = LAYOUT(KC_CIRC, KC_EXLM, KC_LCBR, KC_LBRC, KC_LPRN, KC_MINS, KC_PLUS, KC_RPRN, KC_RBRC, KC_RCBR, KC_SCLN, KC_QUOT, KC_TAB, KC_PIPE, KC_LEFT, LALT(KC_LEFT), LALT(KC_RGHT), LGUI(KC_LEFT), LGUI(KC_RGHT), LALT(KC_LEFT), LALT(KC_RGHT), KC_RGHT, KC_DLR, KC_DQUO, KC_TRNS, KC_BSLS, KC_DOWN, LALT(KC_BSPC), LALT(KC_DEL), KC_LT, KC_GT, LALT(KC_BSPC), LALT(KC_DEL), KC_UP, KC_SLSH, KC_EQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(6), KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_VOLD, KC_VOLU, KC_MFFD),

[_LAYER5] = LAYOUT(KC_1, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_LALT, KC_LALT, KC_7, KC_8, KC_9, KC_SCLN, KC_DEL, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_UNDS, LSA(KC_2), KC_4, KC_5, KC_6, KC_SLSH, KC_BSLS, KC_NO, KC_PLUS, KC_MINS, KC_COMM, KC_COLN, KC_MINS, KC_EQL, KC_1, KC_2, KC_3, KC_0, KC_EQL, TO(0), KC_LCTL, KC_ENT, KC_DOT, KC_BSPC, KC_NO, KC_NO, KC_ENT, KC_PLUS, KC_MINS, KC_UNDS, KC_ASTR),

[_LAYER6] = LAYOUT(KC_TRNS, QK_BOOT, DB_TOGG, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, KC_DEL, KC_TRNS, EE_CLR, MU_NEXT, AU_ON, AU_OFF, AG_NORM, AG_SWAP, DF(0), DF(1), DF(2), DF(5), KC_TRNS, KC_TRNS, AU_PREV, AU_NEXT, MU_ON, MU_OFF, MI_ON, MI_OFF, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS) 

};